// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nerve.Service.Domain;

#nullable disable

namespace Nerve.Service.Migrations
{
    [DbContext(typeof(NerveDbContext))]
    [Migration("20260702213356_AddListDomainCount")]
    partial class AddListDomainCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Nerve.Service.Domain.Counters.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Counters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = 0L
                        },
                        new
                        {
                            Id = 2,
                            Value = 0L
                        },
                        new
                        {
                            Id = 3,
                            Value = 0L
                        });
                });

            modelBuilder.Entity("Nerve.Service.Domain.Domains.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ListId");

                    b.HasIndex("Source");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Domains");
                });

            modelBuilder.Entity("Nerve.Service.Domain.Lists.List", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DomainCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRefreshed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ip");

                    b.HasIndex("Location");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("Nerve.Service.Domain.Queries.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Duration")
                        .HasColumnType("REAL");

                    b.Property<byte>("ResponseCode")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Client");

                    b.HasIndex("Domain");

                    b.HasIndex("Status");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("Nerve.Service.Domain.Resolvers.Resolver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint");

                    b.HasIndex("Protocol");

                    b.ToTable("Resolvers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Endpoint = "https://unfiltered.joindns4.eu/dns-query",
                            Protocol = 1
                        },
                        new
                        {
                            Id = 2,
                            Endpoint = "https://dns.quad9.net/dns-query",
                            Protocol = 1
                        });
                });

            modelBuilder.Entity("Nerve.Service.Domain.Domains.Domain", b =>
                {
                    b.HasOne("Nerve.Service.Domain.Lists.List", "List")
                        .WithMany()
                        .HasForeignKey("ListId");

                    b.Navigation("List");
                });
#pragma warning restore 612, 618
        }
    }
}
